import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Raleway, Manrope } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const raleway = Raleway({ subsets: ["latin"], variable: "--font-raleway" });
const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
  title: "The WeekEnd Coders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} bg-black mx-auto font-manrope sm:max-w-screen-sm md:max-w-screen-md xl:max-w-screen-2xl`}
      >
        {children}
      </body>
    </html>
  );
}
